# config.yaml
data:
  image_dir: "./data/coco/train2017"
  caption_json: "./data/coco/coco_train_captions.json"

train:
  batch_size: 1024
  lr: 5e-5
  epochs: 16
  neg_strategy: hard # light_semantic, hard
  max_samples: 100000   # 注释掉以启用全数据训练